# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    unlock_keychain(
      password: ENV["KEYCHAIN_PASSWORD"]
    )
    api_key = app_store_connect_api_key(
      key_id: "7459U6UPUW",
      issuer_id: "5e03957a-e681-458f-8011-a8f608b71a70",
      key_content: ENV["APP_STORE_KEY"],
      duration: 1200,
      in_house: false,
    )
    match(type: "appstore", git_basic_authorization: ENV["GIT_BASIC_AUTHORIZATION"], api_key: api_key)
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "AsoBMaShow.xcodeproj"
    )
    build_app(
      scheme: "AsoBMaShow",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.SNURhythm.AsoBMaShow" => "match AppStore com.SNURhythm.AsoBMaShow"
        },
        signingStyle: "manual"
      },
      xcargs: "-allowProvisioningUpdates",
      clean: true
    )
    temporary_fix_ios_post_build
    upload_to_testflight
  end
end

desc "Temporary workaround to remove unwanted files from the IPA"
private_lane :temporary_fix_ios_post_build do
  # Workaround to remove ._Symbols from ipa.
  ipa_location = lane_context[SharedValues::IPA_OUTPUT_PATH]
  sh("unzip -l #{ipa_location} | grep ._Symbols || true")
  sh("zip -d #{ipa_location} ._Symbols/ || true")
end
