# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", git_basic_authorization: ENV["GIT_BASIC_AUTHORIZATION"])
    increment_build_number(xcodeproj: "OpenBMS.xcodeproj")
    build_app(
      scheme: "OpenBMS",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.snurhythm.OpenBMS" => "match AppStore com.snurhythm.OpenBMS",
          "org.libsdl.SDL2" => "match AppStore com.snurhythm.OpenBMS",
          "org.libsdl.SDL2-ttf" => "match AppStore com.snurhythm.OpenBMS"
        },
        signingStyle: "manual",
      }
    )
    temporary_fix_ios_post_build
    upload_to_testflight
  end
end

desc "Temporary workaround to remove unwanted files from the IPA"
private_lane :temporary_fix_ios_post_build do
  # Workaround to remove ._Symbols from ipa.
  ipa_location = lane_context[SharedValues::IPA_OUTPUT_PATH]
  sh("unzip -l #{ipa_location} | grep ._Symbols || true")
  sh("zip -d #{ipa_location} ._Symbols/ || true")
end
