# TODO: compile all shaders for all profiles
# example: ./shaderc -f ../shaders/fs_blurV.sc -o ../shaders/metal/fs_blurV.bin --platform osx --type f --profile metal -O 3 --varyingdef ../shaders/yuvrgb.def.sc
