name: Build & Deploy iOS

on:
  push:
    branches:
      - main

jobs:
  appstore:
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    name: Deploy to TestFlight
    runs-on: [self-hosted, macOS]
    timeout-minutes: 30
    strategy:
      matrix:
        ruby: ["3.1.2"]
    steps:
      - run: ./init_bgfx.sh
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          bundler-cache: true
          self-hosted: true
      - uses: actions/cache@v3
        with:
          path: ios/Xcode/OpenBMS/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: cd ios/Xcode/OpenBMS && bundle install && bundle exec pod repo update && bundle exec pod install
      - uses: mikehardy/buildcache-action@v2.1.0
      - working-directory: ./ios/Xcode/OpenBMS
        run: bundle exec fastlane ios beta
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
