name: Build & Deploy iOS

on:
  push:
    branches:
      - main

jobs:
  appstore:
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    name: Deploy to TestFlight
    runs-on: [self-hosted, macOS]
    timeout-minutes: 30
    strategy:
      matrix:
        ruby: ["3.1.2"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      # - run: security unlock-keychain -p '' ~/Library/Keychains/fastlane_tmp.keychain-db && /usr/bin/codesign --force --sign 34880200590025A82E9C5F3532E90943FF2C36D3 --generate-entitlement-der /Users/xf/Library/Developer/Xcode/DerivedData/OpenBMS-ctypzucmvdkvixehhworeabhoarv/Build/Intermediates.noindex/ArchiveIntermediates/OpenBMS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SDL2.framework
      - run: ./init_bgfx.sh
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          bundler-cache: true
          self-hosted: true
      - uses: actions/cache@v3
        with:
          path: ios/Xcode/OpenBMS/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: cd ios/Xcode/OpenBMS && bundle install && bundle exec pod repo update && bundle exec pod install
      # - uses: mikehardy/buildcache-action@v2.1.0
      - working-directory: ./ios/Xcode/OpenBMS
        run: bundle exec fastlane ios beta --verbose
        env:
          FASTLANE_USER: zudevxf@gmail.com
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_BASIC_AUTHORIZATION }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA: 1
